name: Run Selenium Tests
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Java 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
 
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Check Maven version
      run: mvn -v
      
    - name: Set up Maven
      uses: actions/setup-java@v3 # using setup-java to also install Maven
      with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
   
    - name: Run Tests with Maven
      run: mvn clean test
